

delete from unit$deploy_package;
update app_instance set deploy_package='',deploy_package_url='',variable_values='=';


delete from application_domain where guid!=r_guid;
delete from app_instance where guid!=r_guid;
delete from app_system where guid!=r_guid;
delete from app_system_design where guid!=r_guid;
delete from block_storage where guid!=r_guid;
delete from business_zone where guid!=r_guid;
delete from business_zone_design where guid!=r_guid;
delete from cache_instance where guid!=r_guid;
delete from cache_resource_instance where guid!=r_guid;
delete from charge_type where guid!=r_guid;
delete from cloud_vendor where guid!=r_guid;
delete from cluster_node_type where guid!=r_guid;
delete from cluster_type where guid!=r_guid;
delete from cos_instance where guid!=r_guid;
delete from cos_resource_instance where guid!=r_guid;
delete from data_center where guid!=r_guid;
delete from data_center_design where guid!=r_guid;
delete from default_security_policy where guid!=r_guid;
delete from default_security_policy_design where guid!=r_guid;
delete from deploy_environment where guid!=r_guid;
delete from deploy_package where guid!=r_guid;
delete from diff_configuration where guid!=r_guid;
delete from host_resource_instance where guid!=r_guid;
delete from invoke where guid!=r_guid;
delete from invoke_design where guid!=r_guid;
delete from ip_address where guid!=r_guid;
delete from lb_instance where guid!=r_guid;
delete from lb_resource_instance where guid!=r_guid;
delete from legal_person where guid!=r_guid;
delete from manage_role where guid!=r_guid;
delete from network_link where guid!=r_guid;
delete from network_link_design where guid!=r_guid;
delete from network_link_type where guid!=r_guid;
delete from network_segment where guid!=r_guid;
delete from network_segment_design where guid!=r_guid;
delete from network_zone where guid!=r_guid;
delete from network_zone_design where guid!=r_guid;
delete from rdb_instance where guid!=r_guid;
delete from rdb_resource_instance where guid!=r_guid;
delete from resource_instance_spec where guid!=r_guid;
delete from resource_instance_system where guid!=r_guid;
delete from resource_instance_type where guid!=r_guid;
delete from resource_set where guid!=r_guid;
delete from resource_set_design where guid!=r_guid;
delete from resource_set_invoke_design where guid!=r_guid;
delete from route where guid!=r_guid;
delete from route_design where guid!=r_guid;
delete from service_design where guid!=r_guid;
delete from service_invoke_design where guid!=r_guid;
delete from service_invoke_seq_design where guid!=r_guid;
delete from static_diff_conf_value where guid!=r_guid;
delete from storage_type where guid!=r_guid;
delete from subsys where guid!=r_guid;
delete from subsys_design where guid!=r_guid;
delete from unit where guid!=r_guid;
delete from unit_design where guid!=r_guid;
delete from unit_type where guid!=r_guid;






update application_domain set state = 34 where state in(35,36);
update app_instance set state = 34 where state in(35,36);
update app_system set state = 34 where state in(35,36);
update app_system_design set state = 34 where state in(35,36);
update block_storage set state = 34 where state in(35,36);
update business_zone set state = 34 where state in(35,36);
update business_zone_design set state = 34 where state in(35,36);
update cache_instance set state = 34 where state in(35,36);
update cache_resource_instance set state = 34 where state in(35,36);
update charge_type set state = 34 where state in(35,36);
update cloud_vendor set state = 34 where state in(35,36);
update cluster_node_type set state = 34 where state in(35,36);
update cluster_type set state = 34 where state in(35,36);
update cos_instance set state = 34 where state in(35,36);
update cos_resource_instance set state = 34 where state in(35,36);
update data_center set state = 34 where state in(35,36);
update data_center_design set state = 34 where state in(35,36);
update default_security_policy set state = 34 where state in(35,36);
update default_security_policy_design set state = 34 where state in(35,36);
update deploy_environment set state = 34 where state in(35,36);
update deploy_package set state = 34 where state in(35,36);
update diff_configuration set state = 34 where state in(35,36);
update host_resource_instance set state = 34 where state in(35,36);
update invoke set state = 34 where state in(35,36);
update invoke_design set state = 34 where state in(35,36);
update ip_address set state = 34 where state in(35,36);
update lb_instance set state = 34 where state in(35,36);
update lb_resource_instance set state = 34 where state in(35,36);
update legal_person set state = 34 where state in(35,36);
update manage_role set state = 34 where state in(35,36);
update network_link set state = 34 where state in(35,36);
update network_link_design set state = 34 where state in(35,36);
update network_link_type set state = 34 where state in(35,36);
update network_segment set state = 34 where state in(35,36);
update network_segment_design set state = 34 where state in(35,36);
update network_zone set state = 34 where state in(35,36);
update network_zone_design set state = 34 where state in(35,36);
update rdb_instance set state = 34 where state in(35,36);
update rdb_resource_instance set state = 34 where state in(35,36);
update resource_instance_spec set state = 34 where state in(35,36);
update resource_instance_system set state = 34 where state in(35,36);
update resource_instance_type set state = 34 where state in(35,36);
update resource_set set state = 34 where state in(35,36);
update resource_set_design set state = 34 where state in(35,36);
update resource_set_invoke_design set state = 34 where state in(35,36);
update route set state = 34 where state in(35,36);
update route_design set state = 34 where state in(35,36);
update service_design set state = 34 where state in(35,36);
update service_invoke_design set state = 34 where state in(35,36);
update service_invoke_seq_design set state = 34 where state in(35,36);
update static_diff_conf_value set state = 34 where state in(35,36);
update storage_type set state = 34 where state in(35,36);
update subsys set state = 34 where state in(35,36);
update subsys_design set state = 34 where state in(35,36);
update unit set state = 34 where state in(35,36);
update unit_design set state = 34 where state in(35,36);
update unit_type set state = 34 where state in(35,36);





update application_domain set state = 37 where state in(38,39);
update app_instance set state = 37 where state in(38,39);
update app_system set state = 37 where state in(38,39);
update app_system_design set state = 37 where state in(38,39);
update block_storage set state = 37 where state in(38,39);
update business_zone set state = 37 where state in(38,39);
update business_zone_design set state = 37 where state in(38,39);
update cache_instance set state = 37 where state in(38,39);
update cache_resource_instance set state = 37 where state in(38,39);
update charge_type set state = 37 where state in(38,39);
update cloud_vendor set state = 37 where state in(38,39);
update cluster_node_type set state = 37 where state in(38,39);
update cluster_type set state = 37 where state in(38,39);
update cos_instance set state = 37 where state in(38,39);
update cos_resource_instance set state = 37 where state in(38,39);
update data_center set state = 37 where state in(38,39);
update data_center_design set state = 37 where state in(38,39);
update default_security_policy set state = 37 where state in(38,39);
update default_security_policy_design set state = 37 where state in(38,39);
update deploy_environment set state = 37 where state in(38,39);
update deploy_package set state = 37 where state in(38,39);
update diff_configuration set state = 37 where state in(38,39);
update host_resource_instance set state = 37 where state in(38,39);
update invoke set state = 37 where state in(38,39);
update invoke_design set state = 37 where state in(38,39);
update ip_address set state = 37 where state in(38,39);
update lb_instance set state = 37 where state in(38,39);
update lb_resource_instance set state = 37 where state in(38,39);
update legal_person set state = 37 where state in(38,39);
update manage_role set state = 37 where state in(38,39);
update network_link set state = 37 where state in(38,39);
update network_link_design set state = 37 where state in(38,39);
update network_link_type set state = 37 where state in(38,39);
update network_segment set state = 37 where state in(38,39);
update network_segment_design set state = 37 where state in(38,39);
update network_zone set state = 37 where state in(38,39);
update network_zone_design set state = 37 where state in(38,39);
update rdb_instance set state = 37 where state in(38,39);
update rdb_resource_instance set state = 37 where state in(38,39);
update resource_instance_spec set state = 37 where state in(38,39);
update resource_instance_system set state = 37 where state in(38,39);
update resource_instance_type set state = 37 where state in(38,39);
update resource_set set state = 37 where state in(38,39);
update resource_set_design set state = 37 where state in(38,39);
update resource_set_invoke_design set state = 37 where state in(38,39);
update route set state = 37 where state in(38,39);
update route_design set state = 37 where state in(38,39);
update service_design set state = 37 where state in(38,39);
update service_invoke_design set state = 37 where state in(38,39);
update service_invoke_seq_design set state = 37 where state in(38,39);
update static_diff_conf_value set state = 37 where state in(38,39);
update storage_type set state = 37 where state in(38,39);
update subsys set state = 37 where state in(38,39);
update subsys_design set state = 37 where state in(38,39);
update unit set state = 37 where state in(38,39);
update unit_design set state = 37 where state in(38,39);
update unit_type set state = 37 where state in(38,39);





update application_domain set state = 40 where state in(41,42,43,44);
update app_instance set state = 40 where state in(41,42,43,44);
update app_system set state = 40 where state in(41,42,43,44);
update app_system_design set state = 40 where state in(41,42,43,44);
update block_storage set state = 40 where state in(41,42,43,44);
update business_zone set state = 40 where state in(41,42,43,44);
update business_zone_design set state = 40 where state in(41,42,43,44);
update cache_instance set state = 40 where state in(41,42,43,44);
update cache_resource_instance set state = 40 where state in(41,42,43,44);
update charge_type set state = 40 where state in(41,42,43,44);
update cloud_vendor set state = 40 where state in(41,42,43,44);
update cluster_node_type set state = 40 where state in(41,42,43,44);
update cluster_type set state = 40 where state in(41,42,43,44);
update cos_instance set state = 40 where state in(41,42,43,44);
update cos_resource_instance set state = 40 where state in(41,42,43,44);
update data_center set state = 40 where state in(41,42,43,44);
update data_center_design set state = 40 where state in(41,42,43,44);
update default_security_policy set state = 40 where state in(41,42,43,44);
update default_security_policy_design set state = 40 where state in(41,42,43,44);
update deploy_environment set state = 40 where state in(41,42,43,44);
update deploy_package set state = 40 where state in(41,42,43,44);
update diff_configuration set state = 40 where state in(41,42,43,44);
update host_resource_instance set state = 40 where state in(41,42,43,44);
update invoke set state = 40 where state in(41,42,43,44);
update invoke_design set state = 40 where state in(41,42,43,44);
update ip_address set state = 40 where state in(41,42,43,44);
update lb_instance set state = 40 where state in(41,42,43,44);
update lb_resource_instance set state = 40 where state in(41,42,43,44);
update legal_person set state = 40 where state in(41,42,43,44);
update manage_role set state = 40 where state in(41,42,43,44);
update network_link set state = 40 where state in(41,42,43,44);
update network_link_design set state = 40 where state in(41,42,43,44);
update network_link_type set state = 40 where state in(41,42,43,44);
update network_segment set state = 40 where state in(41,42,43,44);
update network_segment_design set state = 40 where state in(41,42,43,44);
update network_zone set state = 40 where state in(41,42,43,44);
update network_zone_design set state = 40 where state in(41,42,43,44);
update rdb_instance set state = 40 where state in(41,42,43,44);
update rdb_resource_instance set state = 40 where state in(41,42,43,44);
update resource_instance_spec set state = 40 where state in(41,42,43,44);
update resource_instance_system set state = 40 where state in(41,42,43,44);
update resource_instance_type set state = 40 where state in(41,42,43,44);
update resource_set set state = 40 where state in(41,42,43,44);
update resource_set_design set state = 40 where state in(41,42,43,44);
update resource_set_invoke_design set state = 40 where state in(41,42,43,44);
update route set state = 40 where state in(41,42,43,44);
update route_design set state = 40 where state in(41,42,43,44);
update service_design set state = 40 where state in(41,42,43,44);
update service_invoke_design set state = 40 where state in(41,42,43,44);
update service_invoke_seq_design set state = 40 where state in(41,42,43,44);
update static_diff_conf_value set state = 40 where state in(41,42,43,44);
update storage_type set state = 40 where state in(41,42,43,44);
update subsys set state = 40 where state in(41,42,43,44);
update subsys_design set state = 40 where state in(41,42,43,44);
update unit set state = 40 where state in(41,42,43,44);
update unit_design set state = 40 where state in(41,42,43,44);
update unit_type set state = 40 where state in(41,42,43,44);



update application_domain set fixed_date = NULL;
update app_instance set fixed_date = NULL;
update app_system set fixed_date = NULL;
update app_system_design set fixed_date = NULL;
update block_storage set fixed_date = NULL;
update business_zone set fixed_date = NULL;
update business_zone_design set fixed_date = NULL;
update cache_instance set fixed_date = NULL;
update cache_resource_instance set fixed_date = NULL;
update charge_type set fixed_date = NULL;
update cloud_vendor set fixed_date = NULL;
update cluster_node_type set fixed_date = NULL;
update cluster_type set fixed_date = NULL;
update cos_instance set fixed_date = NULL;
update cos_resource_instance set fixed_date = NULL;
update data_center set fixed_date = NULL;
update data_center_design set fixed_date = NULL;
update default_security_policy set fixed_date = NULL;
update default_security_policy_design set fixed_date = NULL;
update deploy_environment set fixed_date = NULL;
update deploy_package set fixed_date = NULL;
update diff_configuration set fixed_date = NULL;
update host_resource_instance set fixed_date = NULL;
update invoke set fixed_date = NULL;
update invoke_design set fixed_date = NULL;
update ip_address set fixed_date = NULL;
update lb_instance set fixed_date = NULL;
update lb_resource_instance set fixed_date = NULL;
update legal_person set fixed_date = NULL;
update manage_role set fixed_date = NULL;
update network_link set fixed_date = NULL;
update network_link_design set fixed_date = NULL;
update network_link_type set fixed_date = NULL;
update network_segment set fixed_date = NULL;
update network_segment_design set fixed_date = NULL;
update network_zone set fixed_date = NULL;
update network_zone_design set fixed_date = NULL;
update rdb_instance set fixed_date = NULL;
update rdb_resource_instance set fixed_date = NULL;
update resource_instance_spec set fixed_date = NULL;
update resource_instance_system set fixed_date = NULL;
update resource_instance_type set fixed_date = NULL;
update resource_set set fixed_date = NULL;
update resource_set_design set fixed_date = NULL;
update resource_set_invoke_design set fixed_date = NULL;
update route set fixed_date = NULL;
update route_design set fixed_date = NULL;
update service_design set fixed_date = NULL;
update service_invoke_design set fixed_date = NULL;
update service_invoke_seq_design set fixed_date = NULL;
update static_diff_conf_value set fixed_date = NULL;
update storage_type set fixed_date = NULL;
update subsys set fixed_date = NULL;
update subsys_design set fixed_date = NULL;
update unit set fixed_date = NULL;
update unit_design set fixed_date = NULL;
update unit_type set fixed_date = NULL;



update application_domain set state_code = 'new' where state=34;
update app_instance set state_code = 'new' where state=34;
update app_system set state_code = 'new' where state=34;
update app_system_design set state_code = 'new' where state=34;
update block_storage set state_code = 'new' where state=34;
update business_zone set state_code = 'new' where state=34;
update business_zone_design set state_code = 'new' where state=34;
update cache_instance set state_code = 'new' where state=34;
update cache_resource_instance set state_code = 'new' where state=34;
update charge_type set state_code = 'new' where state=34;
update cloud_vendor set state_code = 'new' where state=34;
update cluster_node_type set state_code = 'new' where state=34;
update cluster_type set state_code = 'new' where state=34;
update cos_instance set state_code = 'new' where state=34;
update cos_resource_instance set state_code = 'new' where state=34;
update data_center set state_code = 'new' where state=34;
update data_center_design set state_code = 'new' where state=34;
update default_security_policy set state_code = 'new' where state=34;
update default_security_policy_design set state_code = 'new' where state=34;
update deploy_environment set state_code = 'new' where state=34;
update deploy_package set state_code = 'new' where state=34;
update diff_configuration set state_code = 'new' where state=34;
update host_resource_instance set state_code = 'new' where state=34;
update invoke set state_code = 'new' where state=34;
update invoke_design set state_code = 'new' where state=34;
update ip_address set state_code = 'new' where state=34;
update lb_instance set state_code = 'new' where state=34;
update lb_resource_instance set state_code = 'new' where state=34;
update legal_person set state_code = 'new' where state=34;
update manage_role set state_code = 'new' where state=34;
update network_link set state_code = 'new' where state=34;
update network_link_design set state_code = 'new' where state=34;
update network_link_type set state_code = 'new' where state=34;
update network_segment set state_code = 'new' where state=34;
update network_segment_design set state_code = 'new' where state=34;
update network_zone set state_code = 'new' where state=34;
update network_zone_design set state_code = 'new' where state=34;
update rdb_instance set state_code = 'new' where state=34;
update rdb_resource_instance set state_code = 'new' where state=34;
update resource_instance_spec set state_code = 'new' where state=34;
update resource_instance_system set state_code = 'new' where state=34;
update resource_instance_type set state_code = 'new' where state=34;
update resource_set set state_code = 'new' where state=34;
update resource_set_design set state_code = 'new' where state=34;
update resource_set_invoke_design set state_code = 'new' where state=34;
update route set state_code = 'new' where state=34;
update route_design set state_code = 'new' where state=34;
update service_design set state_code = 'new' where state=34;
update service_invoke_design set state_code = 'new' where state=34;
update service_invoke_seq_design set state_code = 'new' where state=34;
update static_diff_conf_value set state_code = 'new' where state=34;
update storage_type set state_code = 'new' where state=34;
update subsys set state_code = 'new' where state=34;
update subsys_design set state_code = 'new' where state=34;
update unit set state_code = 'new' where state=34;
update unit_design set state_code = 'new' where state=34;
update unit_type set state_code = 'new' where state=34;




update application_domain set state_code = 'created' where state in(37,40);
update app_instance set state_code = 'created' where state in(37,40);
update app_system set state_code = 'created' where state in(37,40);
update app_system_design set state_code = 'created' where state in(37,40);
update block_storage set state_code = 'created' where state in(37,40);
update business_zone set state_code = 'created' where state in(37,40);
update business_zone_design set state_code = 'created' where state in(37,40);
update cache_instance set state_code = 'created' where state in(37,40);
update cache_resource_instance set state_code = 'created' where state in(37,40);
update charge_type set state_code = 'created' where state in(37,40);
update cloud_vendor set state_code = 'created' where state in(37,40);
update cluster_node_type set state_code = 'created' where state in(37,40);
update cluster_type set state_code = 'created' where state in(37,40);
update cos_instance set state_code = 'created' where state in(37,40);
update cos_resource_instance set state_code = 'created' where state in(37,40);
update data_center set state_code = 'created' where state in(37,40);
update data_center_design set state_code = 'created' where state in(37,40);
update default_security_policy set state_code = 'created' where state in(37,40);
update default_security_policy_design set state_code = 'created' where state in(37,40);
update deploy_environment set state_code = 'created' where state in(37,40);
update deploy_package set state_code = 'created' where state in(37,40);
update diff_configuration set state_code = 'created' where state in(37,40);
update host_resource_instance set state_code = 'created' where state in(37,40);
update invoke set state_code = 'created' where state in(37,40);
update invoke_design set state_code = 'created' where state in(37,40);
update ip_address set state_code = 'created' where state in(37,40);
update lb_instance set state_code = 'created' where state in(37,40);
update lb_resource_instance set state_code = 'created' where state in(37,40);
update legal_person set state_code = 'created' where state in(37,40);
update manage_role set state_code = 'created' where state in(37,40);
update network_link set state_code = 'created' where state in(37,40);
update network_link_design set state_code = 'created' where state in(37,40);
update network_link_type set state_code = 'created' where state in(37,40);
update network_segment set state_code = 'created' where state in(37,40);
update network_segment_design set state_code = 'created' where state in(37,40);
update network_zone set state_code = 'created' where state in(37,40);
update network_zone_design set state_code = 'created' where state in(37,40);
update rdb_instance set state_code = 'created' where state in(37,40);
update rdb_resource_instance set state_code = 'created' where state in(37,40);
update resource_instance_spec set state_code = 'created' where state in(37,40);
update resource_instance_system set state_code = 'created' where state in(37,40);
update resource_instance_type set state_code = 'created' where state in(37,40);
update resource_set set state_code = 'created' where state in(37,40);
update resource_set_design set state_code = 'created' where state in(37,40);
update resource_set_invoke_design set state_code = 'created' where state in(37,40);
update route set state_code = 'created' where state in(37,40);
update route_design set state_code = 'created' where state in(37,40);
update service_design set state_code = 'created' where state in(37,40);
update service_invoke_design set state_code = 'created' where state in(37,40);
update service_invoke_seq_design set state_code = 'created' where state in(37,40);
update static_diff_conf_value set state_code = 'created' where state in(37,40);
update storage_type set state_code = 'created' where state in(37,40);
update subsys set state_code = 'created' where state in(37,40);
update subsys_design set state_code = 'created' where state in(37,40);
update unit set state_code = 'created' where state in(37,40);
update unit_design set state_code = 'created' where state in(37,40);
update unit_type set state_code = 'created' where state in(37,40);



